version: "3.1"

services:
  database:
    container_name: mongo
    image: mongo
    volumes:
      - db_data_container:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/uploads:/usr/src/app/api/uploads
    links:
      - database
    depends_on:
      - database
    restart: on-failure

volumes:
  db_data_container:
